# LEC 3: Revisiting Lists and NumPy Continued

## Back to Lists

In [2]:
a = [ 21, 5, 6.0, 7, 90, 20, 23, 43, 100, 67, 9.5 ]

### Slicing

In [12]:
a[1:7]    # a[start:stop:steps]

[5, 6.0, 7, 90, 20, 23]

In [13]:
a[1:7:2]

[5, 7, 20]

In [14]:
a[:7]

[21, 5, 6.0, 7, 90, 20, 23]

In [15]:
a[2:]

[6.0, 7, 90, 20, 23, 43, 100, 67, 9.5]

In [33]:
a[5:-1]

[20, 23, 43, 100, 67]

In [34]:
a[-1:-3]

[]

In [35]:
a[-1:4]

[]

In [22]:
a[:-1]

[21, 5, 6.0, 7, 90, 20, 23, 43, 100, 67]

In [23]:
a[::-1]

[9.5, 67, 100, 43, 23, 20, 90, 7, 6.0, 5, 21]

In [3]:
a[:]

[21, 5, 6.0, 7, 90, 20, 23, 43, 100, 67, 9.5]

In [4]:
a[::]

[21, 5, 6.0, 7, 90, 20, 23, 43, 100, 67, 9.5]

### Few applications

In [17]:
len(a)

11

In [18]:
sum(a)

391.5

In [20]:
mean = sum(a)/len(a)
mean

35.59090909090909

In [21]:
max(a)

100

In [36]:
a.index(max(a))

8

In [22]:
min(a)

5

In [23]:
sorted(a)   # it does not change the original list

[5, 6.0, 7, 9.5, 20, 21, 23, 43, 67, 90, 100]

In [24]:
sorted(a, reverse = True)

[100, 90, 67, 43, 23, 21, 20, 9.5, 7, 6.0, 5]

In [30]:
a.sort()  # it changes the original list
a

[5, 6.0, 7, 9.5, 20, 21, 23, 43, 67, 90, 100]

In [32]:
a.sort(reverse = True)
a

[100, 90, 67, 43, 23, 21, 20, 9.5, 7, 6.0, 5]

In [27]:
b = ['zakir','abhi','biki','jaya']
sorted(b)

['abhi', 'biki', 'jaya', 'zakir']

In [37]:
c = [2,6,8,6,6,8,8,9,0,1,4]
c.count(6)

3

In [5]:
a = [ 21, 5, 6.0, 7, 90, 20, 23, 43, 100, 67, 9.5 ]
b = [ 54, 7, 78, 89.0, 0.1, 32, 12, 89.9, 32, 6, 2 ]

In [6]:
print(a+b)

[21, 5, 6.0, 7, 90, 20, 23, 43, 100, 67, 9.5, 54, 7, 78, 89.0, 0.1, 32, 12, 89.9, 32, 6, 2]


In [7]:
print(2*a)

[21, 5, 6.0, 7, 90, 20, 23, 43, 100, 67, 9.5, 21, 5, 6.0, 7, 90, 20, 23, 43, 100, 67, 9.5]


## Back to NumPy

In [9]:
import numpy as np

### Iterator on array

In [4]:
a = np.array([2,5,7,9])

In [67]:
for i in a:
    print(i**2)

4
25
49
81


In [66]:
a*a

array([ 4, 25, 49, 81])

In [24]:
# iterating over 2d array

a = np.array([[1,2,3], [4,5,6]])

for i in a:
    print(i)

[1 2 3]
[4 5 6]


In [69]:
for i in np.nditer(a, order = 'F'):
    print(i)

1
4
2
5
3
6


In [70]:
for i in np.nditer(a, order = 'C'):
    print(i)

1
2
3
4
5
6


In [27]:
for i in np.nditer(a, order = 'C'):
    print(i**2,end = ' ')

1 4 9 16 25 36 

### Indexing of arrays

In [50]:
a = np.array([2,5,8,11,14,32,67,0])
print(a[0], a[-1], a[1])

2 0 5


In [10]:
b = np.array([[1,2,3,4], [4,5,6,9], [3,6,9,0], [4,0,1,6],[0,0,9,3]])
print(b[0],b[1],b[-1],b[-2])

[1 2 3 4] [4 5 6 9] [0 0 9 3] [4 0 1 6]


### Slicing of Arrays

In [13]:
a[0:3]   # same as lists

[21, 5, 6.0]

In [12]:
a[::-1]

[9.5, 67, 100, 43, 23, 20, 90, 7, 6.0, 5, 21]

#### Slicing 2D arrays

In [14]:
b[:]  

array([[1, 2, 3, 4],
       [4, 5, 6, 9],
       [3, 6, 9, 0],
       [4, 0, 1, 6],
       [0, 0, 9, 3]])

In [15]:
b[:3]

array([[1, 2, 3, 4],
       [4, 5, 6, 9],
       [3, 6, 9, 0]])

In [16]:
b[::2]

array([[1, 2, 3, 4],
       [3, 6, 9, 0],
       [0, 0, 9, 3]])

In [17]:
b[:-1]

array([[1, 2, 3, 4],
       [4, 5, 6, 9],
       [3, 6, 9, 0],
       [4, 0, 1, 6]])

##### Column slicing

In [63]:
b[:]

array([[1, 2, 3, 4],
       [4, 5, 6, 9],
       [3, 6, 9, 0],
       [4, 0, 1, 6],
       [0, 0, 9, 3]])

In [64]:
b[ : , 0]

array([1, 4, 3, 4, 0])

In [66]:
b[:,-1]

array([4, 9, 0, 6, 3])

*General Structure: A[: : , : :]*

In [67]:
b[:, 1:3]

array([[2, 3],
       [5, 6],
       [6, 9],
       [0, 1],
       [0, 9]])

In [71]:
b[2:4,1:3]

array([[6, 9],
       [0, 1]])

*Slicing by conditional statement*

In [73]:
b[b>3]  #picks elements, returns an 1D array

array([4, 4, 5, 6, 9, 6, 9, 4, 6, 9])

### Swap elements

In [86]:
b

array([[1, 2, 3, 4],
       [4, 5, 6, 9],
       [3, 6, 9, 0],
       [4, 0, 1, 6],
       [0, 0, 9, 3]])

In [87]:
b[[1,2]] = b[[2,1]]
b

array([[1, 2, 3, 4],
       [3, 6, 9, 0],
       [4, 5, 6, 9],
       [4, 0, 1, 6],
       [0, 0, 9, 3]])

### Reshape and flatten

In [88]:
b.shape

(5, 4)

In [94]:
c = b.reshape(4,5)
c

array([[1, 2, 3, 4, 3],
       [6, 9, 0, 4, 5],
       [6, 9, 4, 0, 1],
       [6, 0, 0, 9, 3]])

In [95]:
a

array([ 2,  5,  8, 11, 14, 32, 67,  0])

In [98]:
d = a.reshape(2,4)
d

array([[ 2,  5,  8, 11],
       [14, 32, 67,  0]])

In [103]:
e = b.flatten()
e

array([1, 2, 3, 4, 3, 6, 9, 0, 4, 5, 6, 9, 4, 0, 1, 6, 0, 0, 9, 3])

### Check elements

In [106]:
b

array([[1, 2, 3, 4],
       [3, 6, 9, 0],
       [4, 5, 6, 9],
       [4, 0, 1, 6],
       [0, 0, 9, 3]])

In [105]:
np.all(b,0) # along axis = 0 (column)

array([False, False,  True, False])

In [108]:
np.all(b,1) # along axis = 1 (rows)

array([ True, False,  True, False, False])

### Where is the element

In [109]:
np.where(b==0)  # 1st array row index and 2nd array column index

(array([1, 3, 4, 4], dtype=int64), array([3, 1, 0, 1], dtype=int64))

In [110]:
a

array([ 2,  5,  8, 11, 14, 32, 67,  0])

In [112]:
np.where(a==11)

(array([3], dtype=int64),)

In [20]:
r = np.random.random(size = (3,3))
r

array([[0.18174498, 0.34301389, 0.39618412],
       [0.76480619, 0.21752336, 0.30778674],
       [0.53606091, 0.21044092, 0.61961055]])

In [22]:
np.where(r<0.5,0,r)

array([[0.        , 0.        , 0.        ],
       [0.76480619, 0.        , 0.        ],
       [0.53606091, 0.        , 0.61961055]])

### Insert and delete elements

In [118]:
a

array([ 2,  5,  8, 11, 14, 32, 67,  0])

In [121]:
np.insert(a,4,56)
a

array([ 2,  5,  8, 11, 56, 32, 67,  0])

In [122]:
b

array([[1, 2, 3, 4],
       [3, 6, 9, 0],
       [4, 5, 6, 9],
       [4, 0, 1, 6],
       [0, 0, 9, 3]])

In [124]:
np.insert(b,1,[8,9,0,3], axis=0) # along rows, adding column wise

array([[1, 2, 3, 4],
       [8, 9, 0, 3],
       [3, 6, 9, 0],
       [4, 5, 6, 9],
       [4, 0, 1, 6],
       [0, 0, 9, 3]])

In [126]:
np.insert(b,1,[8,9,0,3,2], axis=1) # along columns,  adding row wise

array([[1, 8, 2, 3, 4],
       [3, 9, 6, 9, 0],
       [4, 0, 5, 6, 9],
       [4, 3, 0, 1, 6],
       [0, 2, 0, 9, 3]])

In [128]:
a

array([ 2,  5,  8, 11, 56, 32, 67,  0])

In [127]:
np.delete(a,2)

array([ 2,  5, 11, 56, 32, 67,  0])

In [131]:
b

array([[1, 2, 3, 4],
       [3, 6, 9, 0],
       [4, 5, 6, 9],
       [4, 0, 1, 6],
       [0, 0, 9, 3]])

In [130]:
np.delete(b,2, axis = 0)

array([[1, 2, 3, 4],
       [3, 6, 9, 0],
       [4, 0, 1, 6],
       [0, 0, 9, 3]])